version: '3'
services:
  restic:
    container_name: restic
    image: ghcr.io/erykio/restic-docker:latest
    hostname: restic # restic snapshots are tied to the hostname of your devices that are backed up
    restart: "no"
    environment:
      RESTIC_REPOSITORY: "s3:s3.us-east-005.backblazeb2.com/kasumierka-k3s"
      RESTIC_PASSWORD: "gqPLtnxtJuey2pb"
      RESTIC_JOB_ARGS: "--iexclude prometheus"
      CHECK_URL: https://hc-ping.com/defb56c0-e507-434b-8973-9501c2f1da56
      AWS_ACCESS_KEY_ID: 005bd0fd33d39ba0000000001
      AWS_SECRET_ACCESS_KEY: K005rKj/pvxKuyxE4ACSt3SP6LaV20Q
    volumes:
      - '/var/lib/rancher/k3s/storage:/data:ro'

# docker run --pull=always --hostname=restic --rm -v "/var/lib/rancher/k3s/storage:/data:ro" -e RESTIC_REPOSITORY="s3:s3.us-east-005.backblazeb2.com/kasumierka-k3s" -e RESTIC_PASSWORD="gqPLtnxtJuey2pb" -e RESTIC_JOB_ARGS="--exclude-file=/opt/ansible_restic_k3s_exclude" -e CHECK_URL="https://hc-ping.com/defb56c0-e507-434b-8973-9501c2f1da56" -e AWS_ACCESS_KEY_ID="005bd0fd33d39ba0000000001" -e AWS_SECRET_ACCESS_KEY="K005rKj/pvxKuyxE4ACSt3SP6LaV20Q" ghcr.io/erykio/restic-docker:latest